Repository apache/cloudstack-primate, pull requests merged in 2020-11, with the labels that each got.

#851 FIX - Show clear the add LDAP account button
  src/components/view/ActionButton.vue
Labels: usability

#855 Allow domain admins to configure resource limits
  src/config/section/project.js
Labels: Severity: Minor, bug

#850 Adding message to deleteKubernetesSupportedVersion
  src/config/section/image.js
  src/locales/en.json
Labels: bug

#862 FIX - Setting tab - Autofocus on the input field
  src/components/view/SettingsTab.vue
Labels: enhancement

#864 deployvm: Hiding networks for basic zones
  src/views/compute/DeployVM.vue
Labels: bug

#868 Display IP address while deleting it
  src/views/AutogenView.vue
Labels: enhancement

#861 FIX - Detail setting tab interface
  src/components/view/DetailSettings.vue
Labels: enhancement

#870 hostinfo: Fixing host hypervisor version
  src/views/infra/HostInfo.vue
Labels: bug

#873 List all suitable/available zones while creating networks
  src/views/network/CreateIsolatedNetworkForm.vue
  src/views/network/CreateL2NetworkForm.vue
  src/views/network/CreateSharedNetworkForm.vue
Labels: Severity: Critical, bug
