Repository apache/cloudstack-primate, pull requests merged in 2020-08, with the labels that each got.

#382 Enabling Role based Users in Projects
  src/components/header/ProjectMenu.vue
  src/components/view/DetailsTab.vue
  src/components/view/InfoCard.vue
  src/components/view/ListView.vue
  src/components/view/ResourceView.vue
  src/config/section/project.js
  src/locales/en.json
  src/store/modules/user.js
  src/views/AutogenView.vue
  src/views/project/AccountsTab.vue
  src/views/project/AddAccountOrUserToProject.vue
  src/views/project/InvitationsTemplate.vue
  src/views/project/ProjectDetailsTab.vue
  src/views/project/iam/ProjectRolePermissionTab.vue
  src/views/project/iam/ProjectRoleTab.vue
Labels: feature

#326 Form to Migrate data between Image stores
  src/components/view/DetailsTab.vue
  src/components/view/ListView.vue
  src/components/widgets/Status.vue
  src/config/section/infra/secondaryStorages.js
  src/config/section/network.js
  src/locales/en.json
  src/views/infra/MigrateData.vue
Labels: feature

#484 Some Spanish translations
  src/components/header/TranslationMenu.vue
  src/config/section/compute.js
  src/locales/en.json
  src/locales/es.json
Labels: enhancement, translations, usability

#608 Allow renaming cluster, host, and storage
  src/config/section/infra/clusters.js
  src/config/section/infra/hosts.js
  src/config/section/infra/primaryStorages.js
  src/locales/en.json
Labels: enhancement
