Repository apache/cloudstack-primate, pull requests merged in 2020-06, with the labels that each got.

#343 Allow configuring IPv6 default guest network when deploying a new Zone
  src/views/infra/zone/ZoneWizardZoneDetailsStep.vue
Labels: enhancement

#330 Add unmanage VM button
  src/config/section/compute.js
  src/locales/en.json
Labels: feature

#364 Add boottype and bootmode to VM instance
  src/views/compute/DeployVM.vue
  src/views/dashboard/CapacityDashboard.vue
Labels: enhancement

#373 Adding pvlan option for l2 and fixing passing none for no pvlan type
  src/locales/en.json
  src/views/network/CreateL2NetworkForm.vue
  src/views/network/CreateSharedNetworkForm.vue
Labels: feature

#444 Fixing ldap form
  src/config/section/config.js
  src/views/iam/AddLdapAccount.vue
Labels: testing

#413 Adding custom Vue to change the vm service offering
  src/config/section/compute.js
  src/views/compute/ScaleVM.vue
  src/views/compute/wizard/ComputeOfferingSelection.vue
  src/views/compute/wizard/ComputeSelection.vue
Labels: testing

#170 Modified forms when SAML is enabled
  src/config/section/account.js
  src/config/section/user.js
  src/locales/en.json
  src/views/iam/AddAccount.vue
  src/views/iam/AddLdapAccount.vue
  src/views/iam/ConfigureSamlSsoAuth.vue
Labels: enhancement, testing
