Repository apache/cloudstack-primate, pull requests merged in 2020-07, with the labels that each got.

#353 UI changes for Dynamic roles improvements
  src/config/section/role.js
  src/locales/en.json
  src/views/iam/CreateRole.vue
  src/views/iam/ImportRole.vue
  src/views/iam/RolePermissionTab.vue
Labels: feature

#298 Quota UI
  src/components/view/InfoCard.vue
  src/components/view/ListView.vue
  src/config/section/plugin/quota.js
  src/locales/en.json
  src/views/AutogenView.vue
  src/views/plugins/quota/EditTariffValueWizard.vue
  src/views/plugins/quota/EmailTemplateDetails.vue
  src/views/plugins/quota/QuotaBalance.vue
  src/views/plugins/quota/QuotaSummary.vue
  src/views/plugins/quota/QuotaSummaryResource.vue
  src/views/plugins/quota/QuotaTariff.vue
  src/views/plugins/quota/QuotaUsage.vue
Labels: feature, testing

#459 Display tab showing the current resource count for domain
  src/components/view/ResourceCountUsage.vue
  src/config/section/account.js
  src/config/section/domain.js
  src/config/section/project.js
  src/locales/en.json
Labels: enhancement, usability

#235 Compute > Instances - Missing extended search functionality
  src/components/view/SearchView.vue
  src/config/router.js
  src/config/section/compute.js
  src/config/section/event.js
  src/config/section/image.js
  src/config/section/infra/routers.js
  src/config/section/network.js
  src/config/section/project.js
  src/config/section/storage.js
  src/locales/en.json
  src/utils/plugins.js
  src/views/AutogenView.vue
Labels: testing, usability

#494 Add internationalization for the login, projects top bar, documentation and report errors
  src/components/header/ProjectMenu.vue
  src/components/page/GlobalFooter.vue
  src/components/widgets/Breadcrumb.vue
  src/locales/en.json
  src/locales/es.json
  src/views/auth/Login.vue
Labels: enhancement, usability

#493 Internationalize state output
  src/components/widgets/Status.vue
Labels: enhancement, translations

#454 autogenview: store API parameters as router query for history
  src/components/view/SearchView.vue
  src/views/AutogenView.vue
Labels: enhancement, usability

#515 Add missing internationalization on instance groups view
  src/config/section/compute.js
  src/locales/en.json
  src/locales/es.json
Labels: enhancement

#514 Add missing internationalization on resources tags and annotations
  src/components/view/InfoCard.vue
  src/locales/en.json
  src/locales/es.json
Labels: enhancement

#524 offerings: Removing tags for offerings
  src/config/section/offering.js
Labels: enhancement

#436 feature: template ovf properties
  src/locales/en.json
  src/views/compute/DeployVM.vue
Labels: feature

#531 Add missing internationlization to search and pagination
  src/components/view/InfoCard.vue
  src/components/view/ListResourceTable.vue
  src/components/view/SearchView.vue
  src/locales/en.json
  src/locales/es.json
  src/views/AutogenView.vue
  src/views/compute/MigrateWizard.vue
  src/views/compute/wizard/AffinityGroupSelection.vue
  src/views/compute/wizard/ComputeOfferingSelection.vue
  src/views/compute/wizard/DiskOfferingSelection.vue
  src/views/compute/wizard/NetworkSelection.vue
  src/views/compute/wizard/SshKeyPairSelection.vue
  src/views/compute/wizard/TemplateIsoRadioGroup.vue
  src/views/image/IsoZones.vue
  src/views/image/TemplateZones.vue
  src/views/infra/network/DedicatedVLANTab.vue
  src/views/infra/network/IpRangesTabManagement.vue
  src/views/infra/network/IpRangesTabPublic.vue
  src/views/infra/network/IpRangesTabStorage.vue
  src/views/infra/network/providers/ProviderListView.vue
  src/views/network/EgressRulesTab.vue
  src/views/network/EnableStaticNat.vue
  src/views/network/FirewallRules.vue
  src/views/network/InternalLBAssignVmForm.vue
  src/views/network/InternalLBAssignedVmTab.vue
  src/views/network/IpAddressesTab.vue
  src/views/network/LoadBalancing.vue
  src/views/network/PortForwarding.vue
  src/views/network/VpcTab.vue
  src/views/network/VpcTiersTab.vue
  src/views/project/AccountsTab.vue
  src/views/project/InvitationsTemplate.vue
Labels: enhancement

#458 Adding quick-view options to list view
  src/components/view/ActionButton.vue
  src/components/view/ListView.vue
  src/components/view/QuickView.vue
  src/config/section/storage.js
  src/views/AutogenView.vue
Labels: usability
