Repository apache/cloudstack-primate, pull requests merged in 2020-12, with the labels that each got.

#877 Showing networks from selected physical network
  src/views/infra/network/IpRangesTabGuest.vue
Labels: Severity: Minor, bug

#874 Add button to enable/disable storage pool
  src/config/section/infra/primaryStorages.js
  src/locales/en.json
Labels: enhancement

#879 Fix showing esxi host label instead of vCentre host
  src/locales/ar.json
  src/locales/ca.json
  src/locales/de_DE.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr_FR.json
  src/locales/hi.json
  src/locales/hu.json
  src/locales/it_IT.json
  src/locales/ja_JP.json
  src/locales/ko_KR.json
  src/locales/nb_NO.json
  src/locales/nl_NL.json
  src/locales/pl.json
  src/locales/pt_BR.json
  src/locales/ru_RU.json
  src/locales/zh_CN.json
  src/views/infra/ClusterAdd.vue
  src/views/infra/HostAdd.vue
Labels: Severity: Minor, bug

#878 createsharednetworkform: Fix for multiple physical networks
  src/views/network/CreateSharedNetworkForm.vue
Labels: Severity: Major, bug

#883 phynetworks: Adding tags and zonename to list & detail view
  src/config/section/infra/phynetworks.js
Labels: Severity: Minor, bug

#884 FIX - Update physical network traffic labels
  src/config/section/infra/phynetworks.js
  src/locales/en.json
  src/views/infra/network/EditTrafficLabel.vue
Labels: bug

#880 Close snapshot form in case of an error
  src/locales/en.json
  src/views/storage/TakeSnapshot.vue
Labels: bug

#886 Disable edit and delete of UI read-only settings
  src/components/view/DetailSettings.vue
Labels: Severity: Minor, bug

#885 createnetworkform: Displaying api errors
  src/views/network/CreateIsolatedNetworkForm.vue
  src/views/network/CreateL2NetworkForm.vue
  src/views/network/CreateSharedNetworkForm.vue
Labels: Severity: Minor, bug

#887 compute: startVirtualMachine - Fetching pods, clusters && hosts from the vm's zone
  src/config/section/compute.js
  src/views/compute/StartVirtualMachine.vue
Labels: bug

#891 Primary Storage: Fix empty server details for SharedMountPoint protocol
  src/views/infra/AddPrimaryStorage.vue
Labels: bug

#894 Add options for OOBM action commands
  src/config/section/infra/hosts.js
Labels: bug, enhancement

#897 Fix label on Zone network setup step
  src/views/infra/zone/ZoneWizardNetworkSetupStep.vue
Labels: bug

#899 Displaying time as per user timezone
  src/components/view/DetailsTab.vue
  src/components/view/InfoCard.vue
  src/components/view/ListView.vue
  src/main.js
  src/store/getters.js
  src/store/modules/user.js
  src/store/mutation-types.js
  src/utils/plugins.js
  src/views/dashboard/CapacityDashboard.vue
  src/views/dashboard/UsageDashboard.vue
Labels: Severity: Minor, bug

#901 createnetwork: Show tabs only when supported networks are determined
  src/views/network/CreateNetwork.vue
Labels: bug, usability

#902 Fixes - Translation, notification, API request
  src/locales/en.json
  src/views/AutogenView.vue
  src/views/infra/AddPrimaryStorage.vue
Labels: Severity: Minor, bug

#876 Handle redirect to sub menu when click parent menu
  src/components/menu/menu.js
Labels: enhancement, usability

#903 Allowing user to use browser timezone
  src/components/header/UserMenu.vue
  src/locales/en.json
  src/store/getters.js
  src/store/modules/app.js
  src/store/modules/user.js
  src/store/mutation-types.js
  src/utils/plugins.js
Labels: enhancement, usability
