Repository apache/cloudstack-primate, pull requests merged in 2020-10, with the labels that each got.

#770 Add rootdisk size on compute offering
  src/views/offering/AddComputeOffering.vue
Labels: enhancement

#795 Adding label for isolationmethod
  src/locales/ar.json
  src/locales/ca.json
  src/locales/de_DE.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr_FR.json
  src/locales/hi.json
  src/locales/hu.json
  src/locales/it_IT.json
  src/locales/ja_JP.json
  src/locales/ko_KR.json
  src/locales/nb_NO.json
  src/locales/nl_NL.json
  src/locales/pl.json
  src/locales/pt_BR.json
  src/locales/ru_RU.json
  src/locales/zh_CN.json
Labels: translations

#777 Set deploy-as-is to default on VMware
  src/views/image/RegisterOrUploadTemplate.vue
Labels: feature

#810 Fixing hosts listview labels
  src/components/view/InfoCard.vue
  src/locales/en.json
Labels: usability

#811 Adding netowrk type filter to listview
  src/config/section/network.js
  src/views/AutogenView.vue
Labels: usability

#800 kubernetesservicetab: Selecting the right ip
  src/views/compute/KubernetesServiceTab.vue
Labels: bug

#804 Adding option to copy resource name and IP
  src/components/view/InfoCard.vue
Labels: usability

#834 Display day name instead of label
  src/views/storage/FormSchedule.vue
Labels: bug

#831 FIX - Private Gateway - Show ACL NAME instead of the UUID
  src/config/section/network.js
Labels: bug, usability

#829 FIX - Config - Add autofocus into the input field
  src/components/view/ListView.vue
Labels: usability

#828 FIX - Private Gateway - Add a link for public IP to go-to private gateway resource
  src/components/view/ListView.vue
Labels: bug

#822 FIX - The "Scheduled" type of events have ever-spinning blue circle icon next to it
  src/components/widgets/Status.vue
Labels: usability

#817 Destroying messages after logout
  src/store/modules/user.js
Labels: bug

#812 infocard: Adding support to redirect to publicip
  src/components/view/InfoCard.vue
Labels: usability

#813 Fix - Incorrect results of list view when refreshing browser
  src/views/AutogenView.vue
Labels: Severity: Major, bug

#821 FIX - Changing project no longer changes the sidebar background/theme
  docs/customize.md
  public/config.json
  src/style/vars.less
  theme.config.js
Labels: bug
